{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyNxUXpV3ZNseBJmXKYFnnn1"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["\n","# **Exceptions**\n","\n","Python uses special objects called **exceptions** to manage errors that arise during a program's execution. Whenever an error occurs that makes Python unsure of what to do next, it creates an **exception object**. If you write code that handles the exception, the program will continue running. If you don't handle the exception, the program will halt and show a **traceback**, which includes a report of the exception that was raised.\n","\n","Exceptions are handled with **try-except blocks**. A **try-except** block asks Python to do something, but it also tells Python what to do if an exception is raised. When you use try-except blocks, your programs will continue running even if things start to go wrong. Instead of tracebacks, which can be confusing for users to read, users will see friendly error messages that you've written.\n","\n","### **Handling the ZeroDivisionError Exception**\n","\n","Let's look at a simple error that causes Python to raise an exception. You probably know that it's impossible to divide a number by zero, but let's ask Python to do it anyway.\n","\n","`division_calculator.py`\n","\n","```python\n","print(5/0)\n","```\n","\n","Python can't do this, so we get a traceback:\n","\n","```\n","traceback (most recent call last):\n","  File \"division_calculator.py\", line 1, in <module>\n","    print(5/0)\n","ZeroDivisionError: division by zero  #1\n","```\n","\n","The error reported in the traceback, **ZeroDivisionError**, is an exception object **#1**. Python creates this kind of object in response to a situation where it can't do what we ask it to. When this happens, Python stops the program and tells us the kind of exception that was raised. We can use this information to modify our program. We'll tell Python what to do when this kind of exception occurs; that way, if it happens again, we'll be prepared."],"metadata":{"id":"ytTIHC-UWJQs"}},{"cell_type":"markdown","source":["### Using try-except Blocks\n","\n","When you think an error may occur, you can write a **try-except block** to handle the exception that might be raised. You tell Python to try running some code, and you tell it what to do if the code results in a particular kind of exception.\n","\n","Here's what a try-except block for handling the `ZeroDivisionError` exception looks like:\n","\n","```python\n","try:\n","    print(5/0)\n","except ZeroDivisionError:\n","    print(\"You can't divide by zero!\")\n","```\n","\n","We put `print(5/0)`, the line that caused the error, inside a **try block**. If the code in a try block works, Python skips over the **except block**. If the code in the try block causes an error, Python looks for an except block whose error matches the one that was raised, and runs the code in that block.\n","\n","In this example, the code in the try block produces a `ZeroDivisionError`, so Python looks for an except block calling it how to respond. Python then runs the code in that block, and the user sees a friendly error message instead of a traceback:\n","\n","```\n","You can't divide by zero!\n","```\n","\n","If more code followed the try-except block, the program would continue running because we told Python how to handle the error. Let's look at an example where catching an error can allow a program to continue running.\n","\n","### Using Exceptions to Prevent Crashes\n","\n","Handling errors correctly is especially important when the program has more work to do after the error occurs. This happens often in programs that prompt users for input. If the program responds to invalid input appropriately, it can prompt for more valid input instead of crashing.\n","\n","Let's create a simple calculator that does only division:\n","\n","`division_calculator.py`\n","\n","```python\n","print(\"Give me two numbers, and I'll divide them.\")\n","print(\"Enter 'q' to quit.\")\n","\n","while True:\n","    first_number = input(\"\\nFirst number: \")  #1\n","    if first_number == 'q':\n","        break\n","    second_number = input(\"Second number: \")  #2\n","    if second_number == 'q':\n","        break\n","    answer = int(first_number) / int(second_number)  #3\n","    print(answer)\n","```\n"],"metadata":{"id":"J1uVrKlFWrbb"}},{"cell_type":"markdown","source":["\n","This program prompts the user to input a first number **#1** and, if the user does not enter `q` to quit, a second number **#2**. We then divide these two numbers to get an answer **#3**. This program does nothing to handle errors, so trying to divide by zero causes it to crash:\n","\n","```\n","Give me two numbers, and I'll divide them.\n","Enter 'q' to quit.\n","\n","First number: 5\n","Second number: 0\n","Traceback (most recent call last):\n","  File \"division_calculator.py\", line 11, in <module>\n","    answer = int(first_number) / int(second_number)\n","ZeroDivisionError: division by zero\n","```\n","\n","It's bad that the program crashed, but it's also not a good idea to let users see tracebacks. Nontechnical users will be confused by them, and in a malicious setting, attackers will learn more than you want them to. For example, they'll know the name of your program file, and they'll see a part of your code that isn't working properly. A skilled attacker can sometimes use this information to determine which kind of attacks to use against your code.\n","\n","### The `else` Block\n","\n","We can make this program more error resistant by wrapping the line that might produce errors in a `try-except` block. The error occurs on the line that performs the division, so that's where we'll put the try-except block. This example also includes an **`else` block**. Any code that depends on the try block executing successfully goes in the `else` block:\n","\n","```python\n","--snip--\n","while True:\n","    --snip--\n","    if second_number == 'q':\n","        break\n","    try:   #1\n","        answer = int(first_number) / int(second_number)\n","    except ZeroDivisionError:   #2\n","        print(\"You can't divide by 0!\")\n","    else:  #3\n","        print(answer)\n","```\n","\n","We ask Python to try to complete the division operation in a **try block** **#1**, which includes only the code that might cause an error. Any code that depends on the try block succeeding is added to the **else block**. In this case, if the division operation is successful, we use the else block to print the result **#3**.\n","\n","The except block tells Python how to respond when a `ZeroDivisionError` arises **#2**. If the try block doesn't succeed because of a division-by-zero error, we print a friendly message telling the user how to avoid this kind of error. The program continues to run, and the user never sees a traceback:\n","\n","```\n","Give me two numbers, and I'll divide them.\n","Enter 'q' to quit.\n","\n","First number: 5\n","Second number: 0\n","You can't divide by 0!\n","\n","First number: 5\n","Second number: 2\n","2.5\n","\n","First number: q\n","```\n","\n","The only code that should go in a **try block** is code that might cause an exception to be raised. Sometimes you'll have additional code that should run only if the try block was successful. This code goes in the **else block**. The except block tells Python what to do in case a certain exception arises when it tries to run the code in the try block.\n","\n","By anticipating likely sources of errors, you can write robust programs that continue to run even when they encounter invalid data and missing resources. Your code will be resistant to innocent user mistakes and malicious attacks.\n","\n","### Handling the `FileNotFoundError` Exception\n","\n","One common issue when working with files is handling missing files. The file you're looking for might be in a different location, the filename might be misspelled, or the file might not exist at all. You can handle all of these situations with a try-except block.\n","\n","Let's try to read a file that doesn't exist. The following program tries to read in the contents of *Alice in Wonderland*, but I haven't saved the file **alice.txt** in the same directory as **alice.py**:\n","\n","`alice.py`\n","\n","```python\n","from pathlib import Path\n","\n","path = Path('alice.txt')\n","contents = path.read_text(encoding='utf-8')\n","```\n","\n","Note that we're using `read_text()` in a slightly different way here than what you saw earlier. The `encoding` argument is needed when your system's default encoding doesn't match the encoding of the file that's being read. This is most likely to happen when reading from a file that wasn't created on your system.\n","\n","Python can't read from a missing file, so it raises an exception:\n","\n","```\n","Traceback (most recent call last):\n","  File \"alice.py\", line 4, in <module>  #1\n","    contents = path.read_text(encoding='utf-8')   #2\n","FileNotFoundError: [Errno 2] No such file or directory: 'alice.txt'\n","File \".../.pathlib.py\", line 1056, in read_text\n","    with self.open(mode='r', encoding=encoding, errors=errors) as f:\n","File \"...\\alice.py\", line 1042, in open\n","    return io.open(self, mode, buffering, encoding, errors, newline)\n","FileNotFoundError: [Errno 2] No such file or directory: 'alice.txt'   #3\n","```\n","\n","This is a longer traceback than the ones we've seen previously, so let's look at how you can make sense of more complex tracebacks. It's often best to start at the very end of the traceback. On the last line, we can see that a **`FileNotFoundError`** exception was raised **#3**. This is important because it tells us what kind of exception to use in the except block that we'll write.\n","\n","Looking back near the beginning of the traceback **#1**, we can see that the error occurred at line 4 in the file **alice.py**. The next line shows the line of code that caused the error **#2**. The rest of the traceback shows some code from the libraries that are involved in opening and reading from files. You don't usually need to read through or understand all of these lines in a traceback.\n","\n","To handle the error that's being raised, the try block will begin with the line that was identified as problematic in the traceback. In our example, this is the line that contains `read_text()`:\n","\n","```python\n","from pathlib import Path\n","\n","path = Path('alice.txt')\n","try:\n","    contents = path.read_text(encoding='utf-8')\n","except FileNotFoundError:   #1\n","    print(f\"Sorry, the file {path} does not exist.\")\n","```\n","\n","In this example, the code in the try block produces a `FileNotFoundError`, so we write an except block that matches that error **#1**. Python then runs the code in that block when the file can't be found, and the result is a friendly error message instead of a traceback:\n","\n","```\n","Sorry, the file alice.txt does not exist.\n","```\n","\n","The program has nothing more to do if the file doesn't exist, so this is all the output we see. Let's build on this example and see how exception handling can help when you're working with more than one file.\n","\n","### Analyzing Text\n","\n","You can analyze text files containing entire books. Many classic works of literature are available as simple text files because they are in the public domain. The text used in this section comes from **Project Gutenberg** (`http://gutenberg.org`). Project Gutenberg maintains a collection of literary works that are available in the public domain, and it's a great resource if you're interested in working with literary texts in your programming projects.\n","\n","\n"],"metadata":{"id":"nCUGVsQJXKpa"}},{"cell_type":"markdown","source":["Let's pull in the text of *Alice in Wonderland* and try to count the number of words in the text. To do this, we'll use the string method `split()`, which by default splits a string wherever it finds any whitespace:\n","\n","```python\n","from pathlib import Path\n","\n","path = Path('alice.txt')\n","try:\n","    contents = path.read_text(encoding='utf-8')\n","except FileNotFoundError:\n","    print(f\"Sorry, the file {path} does not exist.\")\n","else:\n","    # Count the approximate number of words in the file:\n","    words = contents.split()  #1\n","    num_words = len(words)  #2\n","    print(f\"The file {path} has about {num_words} words.\")\n","```\n","\n","I moved the file **alice.txt** to the correct directory, so the try block will work this time. We take the string contents, which now contains the entire text of *Alice in Wonderland* as one long string, and use `split()` to produce a list of all the words in the book **#1**. Using `len()` on this list **#2** gives us a good approximation of the number of words in the original text. Lastly, we print a statement that reports how many words were found in the file. This code is placed in the else block because it only works if the code in the try block was executed successfully.\n","\n","The output tells us how many words are in **alice.txt**:\n","\n","```\n","The file alice.txt has about 29594 words.\n","```\n","\n","The count is a little high because extra information is provided by the publisher in the text file used here, but it's a good approximation of the length of *Alice in Wonderland*.\n","\n","### Working with Multiple Files\n","\n","Let's add more books to analyze, but before we do, let's move the bulk of this program to a function called `count_words()`. This will make it easier to run the analysis for multiple books:\n","\n","`word_count.py`\n","\n","```python\n","from pathlib import Path\n","\n","def count_words(path):\n","    \"\"\"Count the approximate number of words in a file.\"\"\" #1\n","    try:\n","        contents = path.read_text(encoding='utf-8')\n","    except FileNotFoundError:\n","        print(f\"Sorry, the file {path} does not exist.\")\n","    else:\n","        # Count the approximate number of words in the file:\n","        words = contents.split()\n","        num_words = len(words)\n","        print(f\"The file {path} has about {num_words} words.\")\n","\n","path = Path('alice.txt')\n","count_words(path)\n","```\n","\n","Most of this code is unchanged. It's only been indented, and moved into the body of `count_words()`. It's a good habit to keep comments up to date when you're revising a program, so the comment has also been changed to a docstring and reworded slightly **#1**.\n","\n","Now we can write a short loop to count the words in any text we want to analyze. We do this by storing the names of the files we want to analyze in a list, and then we call `count_words()` for each file in the list. We'll try to count the words for *Alice in Wonderland*, *Siddhartha*, *Moby Dick*, and *Little Women*, which are all available in the public domain. I've intentionally left **siddhartha.txt** out of the directory containing **word\\_count.py**, so we can see how well our program handles a missing file:\n","\n","```python\n","from pathlib import Path\n","\n","def count_words(filename):\n","    --snip--\n","\n","filenames = ['alice.txt', 'siddhartha.txt', 'moby_dick.txt',\n","             'little_women.txt']\n","for filename in filenames:\n","    path = Path(filename)  #1\n","    count_words(path)\n","```\n","\n","The names of the files are stored as simple strings. Each string is then converted to a `Path` object **31**, before the call to `count_words()`. The missing **siddhartha.txt** file has no effect on the rest of the program's execution:\n","\n","```\n","The file alice.txt has about 29594 words.\n","Sorry, the file siddhartha.txt does not exist.\n","The file moby_dick.txt has about 215864 words.\n","The file little_women.txt has about 189142 words.\n","```\n","\n","Using the `try-except` block in this example provides two significant advantages. We prevent our users from seeing a traceback, and we let the program continue analyzing the texts it's able to find. If we don't catch the `FileNotFoundError` that **siddhartha.txt** raises, the user would see a full traceback, and the program would stop running after trying to analyze *Siddhartha*. It would never analyze *Moby Dick* or *Little Women*.\n","\n","### **Failing Silently**\n","\n","In the previous example, we informed our users that one of the files was unavailable. But you don't need to report every exception you catch. Sometimes, you'll want the program to fail silently when an exception occurs and continue on as if nothing happened. To make a program fail silently, you write a try block as usual, but you explicitly tell Python to do nothing in the except block. Python has a **`pass` statement** that tells it to do nothing in a block:\n","\n","```python\n","def count_words(path):\n","    \"\"\"Count the approximate number of words in a file.\"\"\"\n","    try:\n","        --snip--\n","    except FileNotFoundError:\n","        pass\n","    else:\n","        --snip--\n","```\n","\n","The only difference between this listing and the previous one is the **`pass` statement** in the except block. Now when a `FileNotFoundError` is raised, the code in the except block runs, but nothing happens. No traceback is produced, and there's no output in response to the error that was raised. Users see the word counts for each file that exists, but they don't see any indication that a file wasn't found:\n","\n","```\n","The file alice.txt has about 29594 words.\n","The file moby_dick.txt has about 215864 words.\n","The file little_women.txt has about 189142 words.\n","```\n","\n","The `pass` statement also acts as a placeholder. It's a reminder that you're choosing to do nothing at a specific point in your program's execution, and that you might want to do something there later. For example, in this program we might decide to write all missing filenames to a file called **missing\\_files.txt**. Our users wouldn't see this file, but we'd be able to read the file and deal with any missing texts.\n","\n","### Deciding Which Errors to Report\n","\n","How do you know when to report an error to your users and when to let your program fail silently? If users know which texts are supposed to be analyzed, they might appreciate a message informing them why some texts were not analyzed. If users expect to see some results but don't know which books are supposed to be analyzed, they might not need to know that some texts were unavailable. Giving users information they aren't looking for can decrease the usability of your program. Python's error-handling structures give you fine-grained control over how much to share with users when things go wrong; it's up to you to decide how much information to share.\n","\n","Well-written, properly tested code is not very prone to internal errors, such as syntax or logical errors. But every time your program depends on something external, such as user input, the existence of a file, or the availability of a network connection, there is a possibility of an exception being raised. A little experience will help you know where to include exception-handling blocks in your program and how much to report to users about errors that arise.\n"],"metadata":{"id":"VxIjSPO8YPOi"}},{"cell_type":"markdown","source":["<div align='center'>\n","==========================================================================================\n","</div>\n","\n","#### **TRY IT YOURSELF**\n","**10-6. Addition:** One common problem when prompting for numerical input occurs when people provide text instead of numbers. When you try to convert the input to an `int`, you'll get a **`ValueError`**. Write a program that prompts for two numbers. Add them together and print the result. Catch the `ValueError` if either input value is not a number, and print a friendly error message. Test your program by entering two numbers and then by entering some text instead of a number.\n","\n","**10-7. Addition Calculator:** Wrap your code from Exercise 10-5 in a `while` loop so the user can continue entering numbers, even if they make a mistake and enter text instead of a number.\n","\n","**10-8. Cats and Dogs:** Make two files, **cats.txt** and **dogs.txt**. Store at least three names of cats in the first file and three names of dogs in the second file. Write a program that tries to read these files and print the contents of the file to the screen. Wrap your code in a `try-except` block to catch the **`FileNotFoundError`**, and print a friendly message if a file is missing. Move one of the files to a different location on your system, and make sure the code in the except block executes properly.\n","\n","**10-9. Silent Cats and Dogs:** Modify your `except` block in Exercise 10-7 to fail silently if either file is missing.\n","\n","**10-10. Common Words:** Visit Project Gutenberg (`https://gutenberg.org`) and find a few texts you'd like to analyze. Download the text files for these works, or copy the raw text from your browser into a text file on your computer.\n","\n","You can use the **`count()`** method to find out how many times a word or phrase appears in a string. For example, the following code counts the number of times 'row' appears in a string:\n","\n","```python\n",">>> line = \"Row, row, row your boat\"\n",">>> line.count('row')\n","2\n",">>> line.lower().count('row')\n","3\n","```\n","\n","Notice that converting the string to lowercase using **`lower()`** catches all appearances of the word you're looking for, regardless of how it's formatted.\n","\n","Write a program that reads the files you found at Project Gutenberg and determines how many times the word 'the' appears in each text. This will be an approximation because it will also count words such as 'then' and 'there'. Try counting 'the ' (with a space in the string), and see how much lower your count is.\n","\n"],"metadata":{"id":"DX3PnBWlaFNr"}},{"cell_type":"markdown","source":["<br><br>\n","\n","<div align=\"center\" style=\"margin-top:10px;\">\n","  <table style=\"margin-top:10px; margin-bottom:10px;\">\n","    <tr>\n","      <td style=\"padding-right:15px;\">   <!-- small space between image and text -->\n","        <img src=\"https://avatars.githubusercontent.com/u/170190067?v=4\"\n","             width=\"150\"\n","             alt=\"Saif Ur Rasool\"\n","             style=\"margin-right:15px;\" />\n","      </td>\n","      <td>\n","        <h1><u>Created by Saif Ur Rasool</u> </h1>\n","        <br><b>\n","        <h6><bold>Professional Profiles:</bold></h6>\n","        •\n","        <a href='https://www.linkedin.com/in/saif-ur-rasool/'>Linkedin</a>\n","        &nbsp;&nbsp;\n","        •\n","        <a href='https://github.com/SaifRasool92'>Github</a>\n","        &nbsp;&nbsp;\n","        •\n","        <a href='https://leetcode.com/u/Saif_Rasool/'>Leetcode</a>\n","        &nbsp;&nbsp;\n","        •\n","        <a href='https://monkeytype.com/profile/Saif_ur_Rasool'>Monkeytype</a>\n","        &nbsp;&nbsp;\n","        •\n","        <a href='https://lablab.ai/u/@Saif_123'>Lablab</a>\n","        &nbsp;&nbsp;\n","        •\n","        <a href='https://www.behance.net/saifrasool2'>Behance</a>\n","        &nbsp;&nbsp;\n","        •\n","        <br><br>\n","        <a href='https://www.duolingo.com/profile/SaifUrRasool'>Duolingo</a>\n","        &nbsp;&nbsp;\n","        •\n","        <a href='https://linktr.ee/Saif_Ur_Rasool'>Linktree</a>\n","        <br><br>\n","        <h6>Certificates:</h6>\n","        •\n","        <a href='https://digitalcredential.stanford.edu/check/09E8FB28F122CE1CB9A59536C67B8BE8508A5898A71233B6641137391929242FSm9lSGxRQXdrNk0zc215OFdac2Z6aGFTNFhTTC84VkNCbWZVb3NYOXZHQ1liQlVN'>SL @Stanford Code In Place '25</a>\n","        &nbsp;&nbsp;\n","        •\n","        <a href='https://certificates.cs50.io/a9fa79dc-ae41-4317-9925-c7734bf4255d.pdf?size=letter'>Harvard CS50x Puzzle Day Winner '25</a>\n","        <br><br>\n","        <h6>Courses Taught:</h6>\n","        •\n","        <a href='https://github.com/SaifRasool92/5PM_Python-Crash_Course_23th_June'>Python Crash Course</a>\n","      </td>\n","    </tr>\n","</table>\n","</div>"],"metadata":{"id":"HWLDLm3l7Mkd"}}]}